# Generated by Django 5.2.7 on 2025-11-11 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('mainpage', '0004_user_slug_alter_tag_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='vote',
            name='value',
            field=models.SmallIntegerField(choices=[(1, 'Up'), (-1, 'Down')]),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('user', 'content_type', 'object_id'), name='unique_vote_per_user_per_object'),
        ),
    ]
